language: python
sudo: false

python:
  - "3.4"
  - "3.5"

virtualenv:
  system_site_packages: false

install:
  - pip install flake8
  - pip install coverage
  - pip install nose
  - python setup.py develop

script:
  - flake8 .
  - nosetests test_utils.py -v -s --with-coverage
